// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trading.Application.DAL.Data;

#nullable disable

namespace Trading.Application.DAL.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20240302211725_initialCommit")]
    partial class initialCommit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Core.Models.PriceEntity", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClosePriceVolumesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HighPriceVolumesId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LastTradedVolume")
                        .HasColumnType("REAL");

                    b.Property<int>("LowPriceVolumesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenPriceVolumesId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotTimeUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeFrame")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PriceId");

                    b.HasIndex("ClosePriceVolumesId");

                    b.HasIndex("HighPriceVolumesId");

                    b.HasIndex("LowPriceVolumesId");

                    b.HasIndex("OpenPriceVolumesId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Core.Models.TradingVolumesEntity", b =>
                {
                    b.Property<int>("VolumesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Ask")
                        .HasColumnType("REAL");

                    b.Property<double>("Bid")
                        .HasColumnType("REAL");

                    b.HasKey("VolumesId");

                    b.ToTable("TradingVolumes");
                });

            modelBuilder.Entity("Core.Models.PriceEntity", b =>
                {
                    b.HasOne("Core.Models.TradingVolumesEntity", "ClosePrice")
                        .WithMany()
                        .HasForeignKey("ClosePriceVolumesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.TradingVolumesEntity", "HighPrice")
                        .WithMany()
                        .HasForeignKey("HighPriceVolumesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.TradingVolumesEntity", "LowPrice")
                        .WithMany()
                        .HasForeignKey("LowPriceVolumesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.TradingVolumesEntity", "OpenPrice")
                        .WithMany()
                        .HasForeignKey("OpenPriceVolumesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClosePrice");

                    b.Navigation("HighPrice");

                    b.Navigation("LowPrice");

                    b.Navigation("OpenPrice");
                });
#pragma warning restore 612, 618
        }
    }
}
