// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trading.Application.DAL.Data;

#nullable disable

namespace Trading.Application.DAL.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    partial class TradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Core.Models.PriceEntity", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClosePriceVolumesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HighPriceVolumesId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LastTradedVolume")
                        .HasColumnType("TEXT");

                    b.Property<int>("LowPriceVolumesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenPriceVolumesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SnapshotTimeUTC")
                        .HasColumnType("TEXT");

                    b.HasKey("PriceId");

                    b.HasIndex("ClosePriceVolumesId");

                    b.HasIndex("HighPriceVolumesId");

                    b.HasIndex("LowPriceVolumesId");

                    b.HasIndex("OpenPriceVolumesId");

                    b.HasIndex("PriceBatchId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("Core.Models.TradingVolumesEntity", b =>
                {
                    b.Property<int>("VolumesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Ask")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Bid")
                        .HasColumnType("TEXT");

                    b.HasKey("VolumesId");

                    b.ToTable("TradingVolumes");
                });

            modelBuilder.Entity("Core.PriceBatch", b =>
                {
                    b.Property<int>("PriceBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeFrame")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PriceBatchId");

                    b.HasIndex("Ticker", "TimeFrame", "Period");

                    b.ToTable("PriceBatches");
                });

            modelBuilder.Entity("Core.Models.PriceEntity", b =>
                {
                    b.HasOne("Core.Models.TradingVolumesEntity", "ClosePrice")
                        .WithMany()
                        .HasForeignKey("ClosePriceVolumesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.TradingVolumesEntity", "HighPrice")
                        .WithMany()
                        .HasForeignKey("HighPriceVolumesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.TradingVolumesEntity", "LowPrice")
                        .WithMany()
                        .HasForeignKey("LowPriceVolumesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.TradingVolumesEntity", "OpenPrice")
                        .WithMany()
                        .HasForeignKey("OpenPriceVolumesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.PriceBatch", "PriceBatch")
                        .WithMany("Prices")
                        .HasForeignKey("PriceBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClosePrice");

                    b.Navigation("HighPrice");

                    b.Navigation("LowPrice");

                    b.Navigation("OpenPrice");

                    b.Navigation("PriceBatch");
                });

            modelBuilder.Entity("Core.PriceBatch", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
